import React from "react";
import Upgrade from "../home/_components/Upgrade";

const PrivacyPage = () => {
  return (
    <div>
      <p className="text-[48px] font-manrope font-bold bg-gradient-to-r from-[#AA823D] via-[#EFE288] to-[#D1B85A] bg-clip-text text-transparent mb-16">
        Privacy Policy
      </p>

      <div className=" text-[#F5F5F5] font-manrope text-base">
        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="mb-4">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy
        </p>
        <p className="mb-4">
          Interpretation and Definitions Interpretation The words of which the
          initial letter is capitalized have meanings defined under the
          following conditions.
        </p>
        <p className="mb-4">
          The following definitions shall have the same meaning regardless of
          whether they appear in singular or in plural.
        </p>
        <p className="mb-4">
          Definitions For the purposes of this Privacy Policy:
        </p>
        <p className="mb-4">
          You means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is
          accessing or using the Service, as applicable. Company (referred to as
          either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to
          subscription.indiasgotlatent.live.
        </p>
        <p className="mb-4">
          Affiliate means an entity that controls, is controlled by or is under
          common control with a party, where “control” means ownership of 50% or
          more of the shares, equity interest or other securities entitled to
          vote for election of directors or other managing authority. Account
          means a unique account created for You to access our Service or parts
          of our Service.
        </p>
        <p className="mb-4">
          Website refers to subscription.indiasgotlatent.live, accessible
          fromsubscription.indiasgotlatent.live Service refers to the Website.
          Country refers to: Uttar Pradesh, India Service Provider means any
          natural or legal person who processes the data on behalf of the
          Company. It refers to third-party companies or individuals employed by
          the Company to facilitate the Service, to provide the Service on
          behalf of the Company, to perform services related to the Service or
          to assist the Company in analyzing how the Service is used.
          Third-party Social Media Service refers to any website or any social
          network website through which a User can log in or create an account
          to use the Service.
        </p>
        <p className="mb-4">
          Personal Data is any information that relates to an identified or
          identifiable individual. Cookies are small files that are placed on
          Your computer, mobile device or any other device by a website,
          containing the details of Your browsing history on that website among
          its many uses.
        </p>
        <p className="mb-4">
          Usage Data refers to data collected automatically, either generated by
          the use of the Service or from the Service infrastructure itself (for
          example, the duration of a page visit).
        </p>
        <p className="mb-4">
          Collecting and Using Your Personal Data Types of Data Collected
          Personal Data While using Our Service, We may ask You to provide Us
          with certain personally identifiable information that can be used to
          contact or identify You. Personally identifiable information may
          include, but is not limited to:
        </p>

        <p className="mb-4">
          Email address First name and last name Phone number Usage Data Usage
          Data Usage Data is collected automatically when using the Service.
        </p>
        <p className="mb-4">
          Usage Data may include information such as Your Device’s Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>

        <p className="mb-4">
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </p>
        <p className="mb-4">
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </p>
        <p className="mb-4">
          You can instruct Your browser to refuse all Cookies or to indicate
          when a Cookie is being sent. However, if You do not accept Cookies,
          You may not be able to use some parts of our Service.
        </p>
        <p className="mb-4">
          Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies
          remain on your personal computer or mobile device when You go offline,
          while Session Cookies are deleted as soon as You close your web
          browser.
        </p>
        <p className="mb-4">
          We use both session and persistent Cookies for the purposes set out
          below:
        </p>
        <p className="mb-4">
          Necessary / Essential CookiesType: Session CookiesAdministered by:
          UsPurpose: These Cookies are essential to provide You with services
          available through the Website and to enable You to use some of its
          features. They help to authenticate users and prevent fraudulent use
          of user accounts. Without these Cookies, the services that You have
          asked for cannot be provided, and We only use these Cookies to provide
          You with those services. Cookies Policy / Notice Acceptance
          CookiesType: Persistent CookiesAdministered by: UsPurpose: These
          Cookies identify if users have accepted the use of cookies on the
          Website. Functionality CookiesType: Persistent CookiesAdministered by:
          UsPurpose: These Cookies allow us to remember choices You make when
          You use the Website, such as remembering your login details or
          language preference. The purpose of these Cookies is to provide You
          with a more personal experience and to avoid You having to re-enter
          your preferences every time You use the Website. For more information
          about the cookies we use and your choices regarding cookies, please
          visit our Cookies Policy.
        </p>
        <p className="mb-4">
          Use of Your Personal Data The Company may use Personal Data for the
          following purposes:
        </p>
        <p className="mb-4">
          To provide and maintain our Service, including to monitor the usage of
          our Service. To manage Your Account: to manage Your registration as a
          user of the Service. The Personal Data You provide can give You access
          to different functionalities of the Service that are available to You
          as a registered user. For the performance of a contract: the
          development, compliance and undertaking of the purchase contract for
          the products, items or services You have purchased or of any other
          contract with Us through the Service. To contact You: To contact You
          by email, telephone calls, SMS, or other equivalent forms of
          electronic communication, such as a mobile application’s push
          notifications regarding updates or informative communications related
          to the functionalities, products or contracted services, including the
          security updates, when necessary or reasonable for their
          implementation. To provide You with news, special offers and general
          information about other goods, services and events which we offer that
          are similar to those that you have already purchased or enquired about
          unless You have opted not to receive such information. To manage Your
          requests: To attend and manage Your requests to Us. We may share your
          personal information in the following situations:
        </p>
        <p className="mb-4">
          With Service Providers: We may share Your personal information with
          Service Providers to monitor and analyze the use of our Service, to
          show advertisements to You to help support and maintain Our Service,
          to contact You, to advertise on third party websites to You after You
          visited our Service or for payment processing.
        </p>
        <p className="mb-4">
          For Business transfers: We may share or transfer Your personal
          information in connection with, or during negotiations of, any merger,
          sale of Company assets, financing, or acquisition of all or a portion
          of our business to another company.
        </p>
        <p className="mb-4">
          With Affiliates: We may share Your information with Our affiliates, in
          which case we will require those affiliates to honor this Privacy
          Policy. Affiliates include Our parent company and any other
          subsidiaries, joint venture partners or other companies that We
          control or that are under common control with Us.
        </p>

        <p className="mb-4">
          With Business partners: We may share Your information with Our
          business partners to offer You certain products, services or
          promotions.
        </p>
        <p className="mb-4">
          With other users: when You share personal information or otherwise
          interact in the public areas with other users, such information may be
          viewed by all users and may be publicly distributed outside. If You
          interact with other users or register through a Third-Party Social
          Media Service, Your contacts on the Third-Party Social Media Service
          may see You name, profile, pictures and description of Your activity.
          Similarly, other users will be able to view descriptions of Your
          activity, communicate with You and view Your profile. Retention of
          Your Personal Data
        </p>
        <p className="mb-4">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </p>
        <p className="mb-4">
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </p>
        <p className="mb-4">
          Transfer of Your Personal Data Your information, including Personal
          Data, is processed at the Company’s operating offices and in any other
          places where the parties involved in the processing are located. It
          means that this information may be transferred to — and maintained on
          — computers located outside of Your state, province, country or other
          governmental jurisdiction where the data protection laws may differ
          from those of Your jurisdiction.
        </p>
        <p className="mb-4">
          Your consent to this Privacy Policy followed by Your submission of such
          information represents Your agreement to that transfer.
        </p>
      </div>
      <Upgrade/>
    </div>
  );
};

export default PrivacyPage;
